module.exports = {
  KARTE_URL: "https://t.karte.io"
  KARTE_BOT_APPLICATION_KEY: ""
  KARTE_BOT_SECRET_KEY: ""
  ALGOLIA_APPLICATION_ID: ""
  ALGOLIA_API_KEY: ""
  ALGOLIA_INDEX_NAME: ""
  A3RT_API_KEY: ""
}